### PR TITLE
GitHub Actions: Let's test multiple builds which might force a rename

### PR DESCRIPTION
**Pull request by cclauss**
@richierockskool Let's try harder to replication your issue...

### CODE REVIEW

**Comment by richierockskool** [comment]
Please check again before I reinstall, everything has be reset and we are back to this now...

homebridge-inkbird-wifi-gateway % npm doctor
Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              ok      current: v9.7.1, latest: v9.7.1
node -v                             ok      current: v20.3.0, recommended: v20.3.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           ok      /usr/local/bin
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
Verify cache contents               ok      verified 1571 tarballs

npm explain npm homebridge-inkbird-wifi-gateway<2028>
npm@9.7.1
node_modules/npm
  npm@"^9.7.1" from the root project

First errors here,

npm explore npm homebridge-inkbird-wifi-gateway

sh: homebridge-inkbird-wifi-gateway: command not found
npm ERR! code 127
npm ERR! path /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/npm
npm ERR! command failed
npm ERR! command sh -c homebridge-inkbird-wifi-gateway

Do I just export PATH? and what do you call it?

Thank you

**Comment by cclauss** [comment]
% `ls ~/Documents/GitHub/homebridge-inkbird-wifi-gateway`

**Comment by richierockskool** [comment]
I have not tried to install yet because I am still getting this error…


***@***.*** homebridge-inkbird-wifi-gateway % ls ~/Documents/GitHub/homebridge-inkbird-wifi-gateway
LICENSE                 Sample-config.json      dist                    package-lock.json       tsconfig.json
README.md               client                  node_modules            package.json
SECURITY.md             config.schema.json      nodemon.json            src
***@***.*** homebridge-inkbird-wifi-gateway % npm explore npm homebridge-inkbird-wifi-gateway
sh: homebridge-inkbird-wifi-gateway: command not found
npm ERR! code 127
npm ERR! path /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/npm
npm ERR! command failed
npm ERR! command sh -c homebridge-inkbird-wifi-gateway

**Comment by richierockskool** [comment]
It load with no path errors and no Homebridge errors except that same one "Failed to load plugins Config Schema"

**Comment by cclauss** [comment]
It looks like the build result is in `node_modules/homebridge-inkbird-wifi-gateway`

**Comment by richierockskool** [comment]
Yes, it is saying no such file or directory, but it was there? how do I get it back in there?

**Comment by richierockskool** [comment]
Not there either?

**Comment by richierockskool** [comment]
Okay it is back in there...node_modules/homebridge-inkbird-wifi-gateway

But, still getting "Failed to Load Plugins Config Schema"?

**Comment by richierockskool** [comment]
What do I have to do from my end? Thank you.

**Comment by richierockskool** [comment]
Looks like everything is working now, thank you for all the help, need to work on src now so the plugin can find the cached accessory.

**Comment by cclauss** [comment]
Do you know what changes made it work?!?

**Comment by richierockskool** [comment]
Hi Christian,

What did we do when NPM Doctor gave this result? PATH?

Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              not ok  Use npm v10.2.5
node -v                             ok      current: v20.10.0, recommended: v20.10.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           ok      /usr/local/bin
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
npm ERR! checkFilesPermission Missing permissions on /usr/local/bin/.keepme (expect: executable)
Perms check on global bin folder    not ok  Check the permissions of files in /usr/local/bin
Verify cache contents               ok      verified 1738 tarballs
npm ERR! Some problems found. See above for recommendations.

**Comment by cclauss** [comment]
> npm ERR! checkFilesPermission Missing permissions on /usr/local/bin/.keepme (expect: executable)

% `chmod +x /usr/local/bin/.keepme`

**Pull request closed without merging**
